POST http://localhost:8000/api/blocksview HTTP/1.1
content-type: application/json

{
    "p1Name":"プレイヤーA",
    "p2Name":"playerB",
    "p1piece":["A","C","D","G","I","J","K","L","N","O","P","R","S","T","U"],
    "p2piece":["A","C","E","G","H","I","K","L","N","O","P","R","S","T","U"],
    "board":[
        [1,0,0,1,1,0,0,0,0,0,0,0,0,0],
        [1,0,0,1,1,0,0,0,0,0,0,0,0,0],
        [1,1,1,0,0,0,0,0,0,0,0,0,0,0],
        [2,2,2,1,0,0,0,0,0,0,0,0,0,0],
        [2,0,0,1,2,0,0,0,0,0,0,0,0,0],
        [2,0,1,1,2,0,0,0,0,0,0,0,0,0],
        [0,2,0,0,1,1,2,0,0,0,0,0,0,0],
        [0,2,2,0,1,1,2,0,0,0,0,0,0,0],
        [0,2,2,0,1,2,2,0,0,0,0,0,0,0],
        [2,0,0,2,2,1,0,0,0,0,0,0,0,0],
        [2,0,0,0,2,1,0,0,0,0,0,0,0,0],
        [2,1,1,1,1,0,0,0,0,0,0,0,0,0],
        [2,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [2,0,0,0,0,0,0,0,0,0,0,0,0,0]
    ],
    "score":{
        "プレイヤーA":1,
        "playerB":2
    }
}



###
POST http://localhost:8000/api/blocksview HTTP/1.1
content-type: application/json

{
    "p1Name":"playerA",
    "p2Name":"playerB",
    "p1piece":["A","C","D","G","I","J","K","L","N","O","P","R","S","T"],
    "p2piece":["A","C","E","G","H","I","K","L","N","O","P","R","S","T","U"],
    "board":[
        [1,0,0,1,1,0,0,0,0,0,0,0,0,0],
        [1,0,0,1,1,0,0,0,0,0,0,0,0,0],
        [1,1,1,0,0,0,0,0,0,0,0,0,0,0],
        [2,2,2,1,0,0,1,0,0,0,0,0,0,0],
        [2,0,0,1,2,1,1,1,0,0,0,0,0,0],
        [2,0,1,1,2,0,1,0,0,0,0,0,0,0],
        [0,2,0,0,1,1,2,0,0,0,0,0,0,0],
        [0,2,2,0,1,1,2,0,0,0,0,0,0,0],
        [0,2,2,0,1,2,2,0,0,0,0,0,0,0],
        [2,0,0,2,2,1,0,0,0,0,0,0,0,0],
        [2,0,0,0,2,1,0,0,0,0,0,0,0,0],
        [2,1,1,1,1,0,0,0,0,0,0,0,0,0],
        [2,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [2,0,0,0,0,0,0,0,0,0,0,0,0,0]
    ],
    "score":{
        "playerA":1,
        "playerB":2
    }
}
###
POST http://localhost:8000/api/blocksview HTTP/1.1
content-type: application/json

{
    "p1Name":"playerA",
    "p2Name":"playerB",
    "p1piece":["A","C","D","G","I","J","K","L","N","O","P","R","S","T"],
    "p2piece":["A","C","E","G","H","I","K","L","N","O","P","R","S","T","U"],
    "board":[
        [1,0,0,1,1,0,0,0,0,0,0,0,0,0],
        [1,0,0,1,1,0,0,0,0,0,0,0,0,0],
        [1,1,1,0,0,0,0,0,0,0,0,0,0,0],
        [2,2,2,1,0,0,1,0,0,0,0,0,0,0],
        [2,0,0,1,2,1,1,1,2,0,0,0,0,0],
        [2,0,1,1,2,0,1,2,2,2,0,0,0,0],
        [0,2,0,0,1,1,2,0,2,0,0,0,0,0],
        [0,2,2,0,1,1,2,0,0,0,0,0,0,0],
        [0,2,2,0,1,2,2,0,0,0,0,0,0,0],
        [2,0,0,2,2,1,0,0,0,0,0,0,0,0],
        [2,0,0,0,2,1,0,0,0,0,0,0,0,0],
        [2,1,1,1,1,0,0,0,0,0,0,0,0,0],
        [2,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [2,0,0,0,0,0,0,0,0,0,0,0,0,0]
    ],
    "score":{
        "playerA":1,
        "playerB":2
    }
}


###
POST http://localhost:8000/api/blocksview/result HTTP/1.1
content-type: application/json

{
    "winName":"ss_tarou"
}